name: FastTwitch
favicon: null
layout_spectrum: 0.89157
typography_spectrum: 0.3556910860352218
title: Fast Twitch
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#2afd48'
    - '#686868'
    - '#b4b4b4'
  brandStrength: 1
  lightness: 0.6875
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
